- name: delete exixting app directory
  ansible.builtin.file:
    path: "{{ app-location }}"
    state: absent

- name: create app directory
  ansible.builtin.file:
    apth: "{{ app-location }}"
    state: directory

- name: "download and extract {{ component }} code"
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: "{{ app-location }}"
    remote_src: yes